FROM gradle:7.6-jdk17 AS builder
WORKDIR /app

COPY build.gradle settings.gradle gradlew ./
COPY gradle gradle
RUN chmod +x ./gradlew && ./gradlew --no-daemon dependencies

COPY . .
RUN ./gradlew --no-daemon clean build -x test

FROM eclipse-temurin:17-jre
WORKDIR /app

EXPOSE 8080

COPY --from=builder /app/build/libs/*.jar app.jar

ENTRYPOINT ["java","-jar","app.jar"]